config/routes.rb
Rails.application.routes.draw do

  root "welcome#welcome"

  resources :parties, only: [:show, :new, :create]
  get "parties/:id/create_giftings" => "parties#create_giftings"
  get "parties/:id/create_giftings_families" => "parties#create_giftings_families"
  post "parties/find" => "parties#find"

  resources :participants, only: [:create, :edit, :update]
  patch "participants/:id/update_preferences" => "participants#update_preferences"
  get "/participants/success" => "participants#success"

  get "/giftings/:id/remind" => "giftings#remind"

  get "confirm/:confirm_token" => "giftings#confirm"

  get "/parties/:id/santas_list_confirm" => "parties#santas_list_confirm"
  get "/parties/:id/santas_list" => "parties#santas_list"
  get "/parties/:id/group_families" => "parties#group_families"

  resources :families, only: [:new, :create, :edit]
end

app/models/party.rb
# == Schema Information
#
# Table name: parties
#
#  id             :integer          not null, primary key
#  name           :string
#  passphrase     :string
#  spending_limit :integer
#  theme          :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  gift_options   :text             default([]), is an Array
#

class Party < ActiveRecord::Base
  include HolidayPassphrase
  include ObfuscateIds

  #---------------------------------------------------------------------
  # Associations
  #---------------------------------------------------------------------

  has_many :participants
  has_many :families, -> { distinct }, through: :participants
  has_many :giftings, through: :participants
  has_many :hosts, -> { hosts }, class_name: Participant

  #---------------------------------------------------------------------
  # Callbacks
  #---------------------------------------------------------------------

  before_create :generate_passphrase

  holiday_passphrase :passphrase

  #---------------------------------------------------------------------
  # Instance Methods
  #---------------------------------------------------------------------

  def sent?
    !giftings.empty?
  end

  # Move to participant model? then no need to
  # have any params
  # Semantically makes more sense to be on the
  # party model though
  def party_guests_not_in_family(participant)
    # participants.reject do |guest|
    #   guest.family.id == participant.family.id
    # end

    family_members = participant.family.participants
    return participants - family_members
  end

end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_action :find_party,
    only: [:show, :create_giftings, :create_giftings_families, :santas_list_confirm, :santas_list, :group_families]

  def show
    @participants = @party.participants
    @participant = Participant.new
  end

  def find
    parties = Party
                .where(passphrase: params[:existing_party][:holiday_passphrase])
                .joins(:participants)
                .where("email = ? AND party_owner = true", params[:existing_party][:email])

    if parties.empty?
      flash[:error] = "no_parties_found"
      redirect_to "/" and return
    end

    if parties.size == 1
      redirect_to "/parties/#{parties.first.encoded_id}" and return
    else
      @parties = parties # Ask user to choose which of their parties to view
    end
  end

  def new
    @party = Party.new
  end

  def create
    party = Party.create(party_params)
    redirect_to "/parties/#{party.encoded_id}"
  end

  def create_giftings
    Giftings::Create.new(@party).call
    # TODO: run in job
    Participants::EmailHosts.new(@party).call
    redirect_to "/participants/success"
  end

  def create_giftings_families
    # TODO: If one family is larger than the rest of
    # the participants added together, there cannot
    # be a pairing
    # Show message asking user to confirm this is okay?
    Giftings::CreateForFamilies.new(@party).call
    # TODO: run in job
    Participants::EmailHosts.new(@party).call
    redirect_to "/participants/success"
  end

  ###### View routes ######

  def santas_list_confirm
  end

  def santas_list
  end

  def group_families
  end

  private

  def party_params
    params.require(:party).permit(:theme, :name, :spending_limit, gift_options: [])
  end

  def find_party
    @party = Party.obj_from_encoded_id(params[:id])
  end

end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/parties/find.html.erb
<% if @parties %>
  <% @parties.each do |party| %>
    <%= link_to "#{party.name}", {:controller => :parties, :action => :show, :id => party.encoded_id} %>
  <%end %>
<% end %>

app/views/parties/group_families.html.erb
<div>
  <div class="border-box">
    <div class="new-family">
      <%= form_for Family.new do |family_form| %>
        <%= hidden_field(:party, :encoded_id, value: @party.encoded_id) %>
          <%= family_form.collection_check_boxes(:participant_ids, @party.participants.without_family, :id, :name ) %>
          <%= family_form.text_field :name, placeholder: "Family Name" %>
        <%= family_form.submit "Add Family", class: "new-family-partial" %>
      <% end %>
    </div>
    <div class="existing-families">
      <%- @party.families.each do |family| %>
        <div class="family">
        <h2><%= family.name %></h2>
          <%- family.participants.each do |participant| %>
            <%= participant.name %>
          <% end %>
        </div>
      <% end %>
    </div>
    <%= button_to "Generate Secret Santas", {:controller => :parties, :action => :create_giftings_families, id: @party.encoded_id}, {:method => :get} %>
  </div>
</div>

app/views/parties/new.html.erb
<div class="border-box">
  <div class="parties-new">
    <%= form_for(@party) do |party| %>
      <h1>Create a new party</h1>
      <%= party.text_field :name, placeholder: "Party name" %>
      <%= party.text_field :theme, placeholder: "Party theme" %>
      <div class="parties-new-spending-limit">
        <div class="parties-new-spending-limit-sign">$</div>
        <div class="parties-new-spending-limit-input">
          <%= party.text_field :spending_limit, placeholder: "Spending Limit" %>
        </div>
      </div>
      <div class="parties-new-submit">
        <%= party.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/parties/santas_list.erb
<h1 class="serif-font santas-list-heading">Santa's List</h1>
<div class="santas-list">
  <div class="border-box">
    <table class="santas-list-table">
      <tr>
        <th>
          Guest
        </th>
        <th>
          Buys for
        </th>
      </tr>
      <%- @party.giftings.each do |gifting| %>
        <tr>
          <td>
            <%= gifting.participant.name %>
          </td>
          <td>
          <%= gifting.giftee.name %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/parties/santas_list_confirm.erb
<div class="santas-list-confirm">
  Are you sure you want to view Santa's master list?
  <%= button_to "View list", {:controller => :parties, :action => :santas_list, id: @party.encoded_id}, {:method => :get} %>
</div>

app/views/parties/show.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>
<div class="border-box">
  <% if @party.sent? %>
    <h1 class="party-show">Your guest list</h1>
  <% else %>
    <h1 class="party-show">Add your guests</h1>
    <p class="party-show-reminder">(Don't forget to add yourself...)</p>
  <% end %>
  <%= render partial:"participants/guest_list" %>
  <% if @party.giftings.empty? %>
    <%= button_to "Generate Secret Santas", {:controller => :parties, :action => :create_giftings, id: @party.encoded_id}, {:method => :get} %>
    <%= button_to "Group into Families", {:controller => :parties, :action => :group_families, id: @party.encoded_id}, {:method => :get} %>
  <% end %>
</div>